//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
// 
#pragma warning disable 1591

namespace Gurkan.SAPWAS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'EndpointReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/08/addressing' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZGURKAN_F_V15", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZGURKAN_F_V15 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZGURKAN_GET_SAP_DATAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZGURKAN_SET_SQL_DATAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZGURKAN_TESTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZGURKAN_F_V15() {
            this.Url = global::Gurkan.Properties.Settings.Default.Gurkan_SAPWAS_ZGURKAN_F_V15;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZGURKAN_GET_SAP_DATACompletedEventHandler ZGURKAN_GET_SAP_DATACompleted;
        
        /// <remarks/>
        public event ZGURKAN_SET_SQL_DATACompletedEventHandler ZGURKAN_SET_SQL_DATACompleted;
        
        /// <remarks/>
        public event ZGURKAN_TESTCompletedEventHandler ZGURKAN_TESTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("E_KANTAR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZGURKAN01[] ZGURKAN_GET_SAP_DATA([System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out ZGURKAN_S_KNA1[] E_KNA1, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out ZGURKAN_S_LFA1[] E_LFA1, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out ZGURKAN_S_LIKP[] E_LIKP, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out ZGURKAN_S_MARA[] E_MARA) {
            object[] results = this.Invoke("ZGURKAN_GET_SAP_DATA", new object[0]);
            E_KNA1 = ((ZGURKAN_S_KNA1[])(results[1]));
            E_LFA1 = ((ZGURKAN_S_LFA1[])(results[2]));
            E_LIKP = ((ZGURKAN_S_LIKP[])(results[3]));
            E_MARA = ((ZGURKAN_S_MARA[])(results[4]));
            return ((ZGURKAN01[])(results[0]));
        }
        
        /// <remarks/>
        public void ZGURKAN_GET_SAP_DATAAsync() {
            this.ZGURKAN_GET_SAP_DATAAsync(null);
        }
        
        /// <remarks/>
        public void ZGURKAN_GET_SAP_DATAAsync(object userState) {
            if ((this.ZGURKAN_GET_SAP_DATAOperationCompleted == null)) {
                this.ZGURKAN_GET_SAP_DATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZGURKAN_GET_SAP_DATAOperationCompleted);
            }
            this.InvokeAsync("ZGURKAN_GET_SAP_DATA", new object[0], this.ZGURKAN_GET_SAP_DATAOperationCompleted, userState);
        }
        
        private void OnZGURKAN_GET_SAP_DATAOperationCompleted(object arg) {
            if ((this.ZGURKAN_GET_SAP_DATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZGURKAN_GET_SAP_DATACompleted(this, new ZGURKAN_GET_SAP_DATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ZGURKAN_SET_SQL_DATA([System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] ZGURKAN_S_TARTIM_TRANSFER[] I_TARTIM) {
            this.Invoke("ZGURKAN_SET_SQL_DATA", new object[] {
                        I_TARTIM});
        }
        
        /// <remarks/>
        public void ZGURKAN_SET_SQL_DATAAsync(ZGURKAN_S_TARTIM_TRANSFER[] I_TARTIM) {
            this.ZGURKAN_SET_SQL_DATAAsync(I_TARTIM, null);
        }
        
        /// <remarks/>
        public void ZGURKAN_SET_SQL_DATAAsync(ZGURKAN_S_TARTIM_TRANSFER[] I_TARTIM, object userState) {
            if ((this.ZGURKAN_SET_SQL_DATAOperationCompleted == null)) {
                this.ZGURKAN_SET_SQL_DATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZGURKAN_SET_SQL_DATAOperationCompleted);
            }
            this.InvokeAsync("ZGURKAN_SET_SQL_DATA", new object[] {
                        I_TARTIM}, this.ZGURKAN_SET_SQL_DATAOperationCompleted, userState);
        }
        
        private void OnZGURKAN_SET_SQL_DATAOperationCompleted(object arg) {
            if ((this.ZGURKAN_SET_SQL_DATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZGURKAN_SET_SQL_DATACompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sap-com:document:sap:rfc:functions", ResponseNamespace="urn:sap-com:document:sap:rfc:functions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("E_TEXT_AR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZGURKAN_TEST([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string E_TEXT_TR) {
            object[] results = this.Invoke("ZGURKAN_TEST", new object[0]);
            E_TEXT_TR = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZGURKAN_TESTAsync() {
            this.ZGURKAN_TESTAsync(null);
        }
        
        /// <remarks/>
        public void ZGURKAN_TESTAsync(object userState) {
            if ((this.ZGURKAN_TESTOperationCompleted == null)) {
                this.ZGURKAN_TESTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZGURKAN_TESTOperationCompleted);
            }
            this.InvokeAsync("ZGURKAN_TEST", new object[0], this.ZGURKAN_TESTOperationCompleted, userState);
        }
        
        private void OnZGURKAN_TESTOperationCompleted(object arg) {
            if ((this.ZGURKAN_TESTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZGURKAN_TESTCompleted(this, new ZGURKAN_TESTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZGURKAN01 {
        
        private string mANDTField;
        
        private string kANIDField;
        
        private string kANTXField;
        
        private decimal sALOTField;
        
        private decimal sAHITField;
        
        private string mODELField;
        
        private string cOMPOField;
        
        private int bAUDRField;
        
        private int dATABField;
        
        private string pARITField;
        
        private string sTOPBField;
        
        private string fREEMField;
        
        private string aDRE1Field;
        
        private string aDRE2Field;
        
        private string aDRE3Field;
        
        private string aDRE4Field;
        
        private string aDRE5Field;
        
        private string aDRE6Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MANDT {
            get {
                return this.mANDTField;
            }
            set {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KANID {
            get {
                return this.kANIDField;
            }
            set {
                this.kANIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KANTX {
            get {
                return this.kANTXField;
            }
            set {
                this.kANTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SALOT {
            get {
                return this.sALOTField;
            }
            set {
                this.sALOTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SAHIT {
            get {
                return this.sAHITField;
            }
            set {
                this.sAHITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MODEL {
            get {
                return this.mODELField;
            }
            set {
                this.mODELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMPO {
            get {
                return this.cOMPOField;
            }
            set {
                this.cOMPOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int BAUDR {
            get {
                return this.bAUDRField;
            }
            set {
                this.bAUDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DATAB {
            get {
                return this.dATABField;
            }
            set {
                this.dATABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PARIT {
            get {
                return this.pARITField;
            }
            set {
                this.pARITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STOPB {
            get {
                return this.sTOPBField;
            }
            set {
                this.sTOPBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FREEM {
            get {
                return this.fREEMField;
            }
            set {
                this.fREEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADRE1 {
            get {
                return this.aDRE1Field;
            }
            set {
                this.aDRE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADRE2 {
            get {
                return this.aDRE2Field;
            }
            set {
                this.aDRE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADRE3 {
            get {
                return this.aDRE3Field;
            }
            set {
                this.aDRE3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADRE4 {
            get {
                return this.aDRE4Field;
            }
            set {
                this.aDRE4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADRE5 {
            get {
                return this.aDRE5Field;
            }
            set {
                this.aDRE5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADRE6 {
            get {
                return this.aDRE6Field;
            }
            set {
                this.aDRE6Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZGURKAN_S_TARTIM_TRANSFER {
        
        private string kANIDField;
        
        private string tARIDField;
        
        private string tARTIField;
        
        private string tRAIDField;
        
        private string bELGEField;
        
        private string mUHIDField;
        
        private string nAME1_TRField;
        
        private string nAME1_ARField;
        
        private string mATNRField;
        
        private string mAKTX_TRField;
        
        private string mAKTX_ARField;
        
        private string lIFSPField;
        
        private string nAKTRField;
        
        private string nAKARField;
        
        private string gELALField;
        
        private string gITALField;
        
        private string sTEXTField;
        
        private decimal dARAAField;
        
        private string mEINSField;
        
        private decimal aGIR1Field;
        
        private string eRDA1Field;
        
        private string eRZE1Field;
        
        private decimal aGIR2Field;
        
        private string eRDA2Field;
        
        private string eRZE2Field;
        
        private decimal nETAGField;
        
        private decimal bELAGField;
        
        private string lOEKZField;
        
        private string mUBELField;
        
        private string oPERAField;
        
        private string dRIVEField;
        
        private int bAGCOField;
        
        private string wTEXT_TRField;
        
        private string wTEXT_ARField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KANID {
            get {
                return this.kANIDField;
            }
            set {
                this.kANIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TARID {
            get {
                return this.tARIDField;
            }
            set {
                this.tARIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TARTI {
            get {
                return this.tARTIField;
            }
            set {
                this.tARTIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRAID {
            get {
                return this.tRAIDField;
            }
            set {
                this.tRAIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BELGE {
            get {
                return this.bELGEField;
            }
            set {
                this.bELGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MUHID {
            get {
                return this.mUHIDField;
            }
            set {
                this.mUHIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1_TR {
            get {
                return this.nAME1_TRField;
            }
            set {
                this.nAME1_TRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1_AR {
            get {
                return this.nAME1_ARField;
            }
            set {
                this.nAME1_ARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX_TR {
            get {
                return this.mAKTX_TRField;
            }
            set {
                this.mAKTX_TRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX_AR {
            get {
                return this.mAKTX_ARField;
            }
            set {
                this.mAKTX_ARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFSP {
            get {
                return this.lIFSPField;
            }
            set {
                this.lIFSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAKTR {
            get {
                return this.nAKTRField;
            }
            set {
                this.nAKTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAKAR {
            get {
                return this.nAKARField;
            }
            set {
                this.nAKARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GELAL {
            get {
                return this.gELALField;
            }
            set {
                this.gELALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GITAL {
            get {
                return this.gITALField;
            }
            set {
                this.gITALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STEXT {
            get {
                return this.sTEXTField;
            }
            set {
                this.sTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DARAA {
            get {
                return this.dARAAField;
            }
            set {
                this.dARAAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AGIR1 {
            get {
                return this.aGIR1Field;
            }
            set {
                this.aGIR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERDA1 {
            get {
                return this.eRDA1Field;
            }
            set {
                this.eRDA1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERZE1 {
            get {
                return this.eRZE1Field;
            }
            set {
                this.eRZE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AGIR2 {
            get {
                return this.aGIR2Field;
            }
            set {
                this.aGIR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERDA2 {
            get {
                return this.eRDA2Field;
            }
            set {
                this.eRDA2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ERZE2 {
            get {
                return this.eRZE2Field;
            }
            set {
                this.eRZE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NETAG {
            get {
                return this.nETAGField;
            }
            set {
                this.nETAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BELAG {
            get {
                return this.bELAGField;
            }
            set {
                this.bELAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOEKZ {
            get {
                return this.lOEKZField;
            }
            set {
                this.lOEKZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MUBEL {
            get {
                return this.mUBELField;
            }
            set {
                this.mUBELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPERA {
            get {
                return this.oPERAField;
            }
            set {
                this.oPERAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DRIVE {
            get {
                return this.dRIVEField;
            }
            set {
                this.dRIVEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int BAGCO {
            get {
                return this.bAGCOField;
            }
            set {
                this.bAGCOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WTEXT_TR {
            get {
                return this.wTEXT_TRField;
            }
            set {
                this.wTEXT_TRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WTEXT_AR {
            get {
                return this.wTEXT_ARField;
            }
            set {
                this.wTEXT_ARField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZGURKAN_S_MARA {
        
        private string mATNRField;
        
        private string mAKTX_TRField;
        
        private string mAKTX_ARField;
        
        private string mATKLField;
        
        private string wGBEZ_TRField;
        
        private string wGBEZ_ARField;
        
        private string sELLAField;
        
        private string lOLICField;
        
        private int lOLIMField;
        
        private string lOLIAField;
        
        private string uPLICField;
        
        private int uPLIMField;
        
        private string uPLIAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX_TR {
            get {
                return this.mAKTX_TRField;
            }
            set {
                this.mAKTX_TRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MAKTX_AR {
            get {
                return this.mAKTX_ARField;
            }
            set {
                this.mAKTX_ARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATKL {
            get {
                return this.mATKLField;
            }
            set {
                this.mATKLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WGBEZ_TR {
            get {
                return this.wGBEZ_TRField;
            }
            set {
                this.wGBEZ_TRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WGBEZ_AR {
            get {
                return this.wGBEZ_ARField;
            }
            set {
                this.wGBEZ_ARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SELLA {
            get {
                return this.sELLAField;
            }
            set {
                this.sELLAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOLIC {
            get {
                return this.lOLICField;
            }
            set {
                this.lOLICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int LOLIM {
            get {
                return this.lOLIMField;
            }
            set {
                this.lOLIMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOLIA {
            get {
                return this.lOLIAField;
            }
            set {
                this.lOLIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UPLIC {
            get {
                return this.uPLICField;
            }
            set {
                this.uPLICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int UPLIM {
            get {
                return this.uPLIMField;
            }
            set {
                this.uPLIMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UPLIA {
            get {
                return this.uPLIAField;
            }
            set {
                this.uPLIAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZGURKAN_S_LIKP {
        
        private string vBELNField;
        
        private string mATNRField;
        
        private decimal lFIMGField;
        
        private string mEINSField;
        
        private string kUNWEField;
        
        private string lIFSPField;
        
        private string tRAIDField;
        
        private string lFDATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LFIMG {
            get {
                return this.lFIMGField;
            }
            set {
                this.lFIMGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KUNWE {
            get {
                return this.kUNWEField;
            }
            set {
                this.kUNWEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFSP {
            get {
                return this.lIFSPField;
            }
            set {
                this.lIFSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRAID {
            get {
                return this.tRAIDField;
            }
            set {
                this.tRAIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LFDAT {
            get {
                return this.lFDATField;
            }
            set {
                this.lFDATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZGURKAN_S_LFA1 {
        
        private string lIFNRField;
        
        private string nAME1_TRField;
        
        private string nAME1_ARField;
        
        private string vENDOField;
        
        private string tRANSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1_TR {
            get {
                return this.nAME1_TRField;
            }
            set {
                this.nAME1_TRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1_AR {
            get {
                return this.nAME1_ARField;
            }
            set {
                this.nAME1_ARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VENDO {
            get {
                return this.vENDOField;
            }
            set {
                this.vENDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANS {
            get {
                return this.tRANSField;
            }
            set {
                this.tRANSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZGURKAN_S_KNA1 {
        
        private string kUNNRField;
        
        private string nAME1_TRField;
        
        private string nAME1_ARField;
        
        private string aDDRE_TRField;
        
        private string aDDRE_ARField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1_TR {
            get {
                return this.nAME1_TRField;
            }
            set {
                this.nAME1_TRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1_AR {
            get {
                return this.nAME1_ARField;
            }
            set {
                this.nAME1_ARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRE_TR {
            get {
                return this.aDDRE_TRField;
            }
            set {
                this.aDDRE_TRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDRE_AR {
            get {
                return this.aDDRE_ARField;
            }
            set {
                this.aDDRE_ARField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ZGURKAN_GET_SAP_DATACompletedEventHandler(object sender, ZGURKAN_GET_SAP_DATACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZGURKAN_GET_SAP_DATACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZGURKAN_GET_SAP_DATACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZGURKAN01[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZGURKAN01[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ZGURKAN_S_KNA1[] E_KNA1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZGURKAN_S_KNA1[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public ZGURKAN_S_LFA1[] E_LFA1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZGURKAN_S_LFA1[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public ZGURKAN_S_LIKP[] E_LIKP {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZGURKAN_S_LIKP[])(this.results[3]));
            }
        }
        
        /// <remarks/>
        public ZGURKAN_S_MARA[] E_MARA {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZGURKAN_S_MARA[])(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ZGURKAN_SET_SQL_DATACompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ZGURKAN_TESTCompletedEventHandler(object sender, ZGURKAN_TESTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZGURKAN_TESTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZGURKAN_TESTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string E_TEXT_TR {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591